### PR TITLE
Fix lints

### PR DESCRIPTION
**Pull request by mklein994**
See #232 

Once these are fixed, travis can start showing real build errors.

### CODE REVIEW

**Comment by mklein994** [comment]
@hjalmers If I change back `gt-generic-table` to `generic-table`, would that work? The prefix is to reduce conflict with other projects using this library, but since this has been established, I don't think it would be a problem to keep the old selector (`generic-table`).

**Comment by mklein994** [comment]
I just re-read your comment again; I think it's possible to remove the prefix altogether, but then certain selectors would conflict with HTML5 tags (such as `menu.component.ts` with [`<menu>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu)).

I wonder if it's possible to have a prefix for the website project, but not for `@angular-generic-table/core` or `@angular-generic-table/column-settings`?

**Comment by mklein994** [comment]
I know you're in the middle of transitioning to `ng-packagr`, but how about [multiple apps](https://github.com/angular/angular-cli/wiki/stories-multiple-apps)? TSLint supports multiple `tslint.json` files. Here's an example to put in `@angular-generic-table/tslint.json`:

```json
{
  "extends": "../tslint.json",
  "rules": {
    "directive-selector": [true, "attribute", "", "camelCase"],
    "component-selector": [true, "element", "", "kebab-case"]
  }
}
```

**Comment by hjalmers** [comment]
Yeah, just found a similar thread on [stackoverflow](https://stackoverflow.com/questions/41248142/angular2-how-to-change-the-default-prefix-of-component-to-stop-tslint-warnings) and thought about adding multiple prefixes to solve the issue (one could be `generic` and another one `gt`). It's good practice to have prefixes of course so perhaps the examples could have `gt-demo` or something where needed. In most cases we should be able to remove the selector altogether as they're not used for the examples i.e. 
```ts
import { Component, OnInit } from '@angular/core';
import { GtConfig, GtRow } from '@angular-generic-table/core';
export interface RowData extends GtRow {
	id: number;
	name: string;
	sales: number;
	meetings: number;
}
@Component({
	selector: 'aggregate',
	templateUrl: './aggregate.component.html',
	styles: []
})
```
could be changed to just
```ts
import { Component, OnInit } from '@angular/core';
import { GtConfig, GtRow } from '@angular-generic-table/core';
export interface RowData extends GtRow {
	id: number;
	name: string;
	sales: number;
	meetings: number;
}
@Component({
	templateUrl: './aggregate.component.html',
	styles: []
})
```

**Comment by hjalmers** [comment]
I went through the files and did some changes but skipped most of the examples as they will be updated/changed anyways. To make the examples clearer I think it would be better to avoid prefixes like `gt` or `generic` as it might be confusing and hard to know if they're part of the library or not. One option might be to add `example` as a prefix for all the examples in the src directory, what do you think? For now i used `*` for examples and `gt` and `generic` for the lib. Also I noticed that the build seems to fail due to missing write permissions now? I'm not that familiar with Travis yet...

**Comment by mklein994** [comment]
I think using the default `app` prefix for everything in `src/` would be ideal, since that is the default (makes it easier to copy and paste). The `gt` prefix is nice, since it's short, so that's good for `@angular-generic-table/core` and `@angular-generic-table/column-settings`.

This is just a hunch, but I think travis is failing because of something happening with `npm run link-lib`. I've tried some stuff on a separate branch, and when I don't cache `~/.npm` or `node_modules`, it works. Note that `ng-packagr` fails still when running `npm run build:core`, even though it says it's a success (There's no output like there is in `npm run build:column-settings`).

**Comment by mklein994** [comment]
@hjalmers I just rebased to fix some stuff in the build. The prefix thing is just changing `"*"` to `""` for now, because TSLint doesn't parse that correctly, and they basically mean the same thing. My preference is still to use `app` as the prefix for examples (if needed) and the website project (everything under `src/`), because then things like `ng generate component` automatically add the prefix, and it doesn't conflict with other stuff.

**Comment by hjalmers** [comment]
Sounds good, I think using ’app’ as a prefix is a good Idea too as it’s the default setting when using angular-cli so a lot of people should recognize it and not mix them up with something from the library. Did you manage to get ng-packagr to build the core btw? I didn’t have time to investigate it yesterday but noticed it failed without any error. Would be nice to release a patch with a few of the fixes before I leave on my holiday:)

**Comment by mklein994** [comment]
@hjalmers You also mentioned removing the selectors from the examples, since they aren't being used. I can do that if you want.

**Comment by hjalmers** [comment]
Well you don’t have to put to much time going through the examples as they’ll need to change anyway. And the prefix for the lib should accept both `gt` and `generic` as prefixes (like it is configured now), otherwise selectors that aren’t used can be removed:) I think the prefix in angular-cli.json is only used for generating new components so it’s going to be wrong for the lib to set it to `app` but it’s easy to change auto generated components and I think creating examples and demo components is going to be a more common use case anyways so we should probably set it to `app`.

**Comment by mklein994** [comment]
Yeah; the way `@angular-generic-table/tslint.json` looks in master right now is good to me. Your logic about `.angular-cli.json` makes sense, but hasn't been applied yet (it still has `"prefix": "gt"`).

If you apply the changes like I have here (mklein994/angular-generic-table@deff092), that would do it.

**Comment by mklein994** [comment]
@hjalmers I was looking through the `.editorconfig` file again, and noticed that it's not parsing the settings correctly. This is how it should be, if you're alright with html files being indented with tabs:

```diff
diff --git a/.editorconfig b/.editorconfig
old mode 100644
new mode 100755
index a8db2da..c0ee290
--- a/.editorconfig
+++ b/.editorconfig
@@ -3,19 +3,18 @@ root = true
 
 [*]
 charset = utf-8
-indent_style = space
+indent_style = tab
 indent_size = 2
 end_of_line = lf
 insert_final_newline = true
 trim_trailing_whitespace = true
 
-[*.{ts,json,scss,md},!{package{,-lock},.vscode/*}.json]
-indent_style = tab
+[*.{ts,scss,html}]
 max_line_length = 80
 
-# YAML files require space indentation
+# YAML files require space indentation.
 # (http://yaml.org/spec/1.2/spec.html#id2777534)
-[*.{yml,yaml}]
+[{*.{yml,yaml},package{,-lock}.json}]
 indent_style = space
 indent_size = 2
 

```

**Pull request merged**
