### PR TITLE
Add the settingsEditable parameter

### PR DESCRIPTION
**Pull request by thomasnisole**
Hey @hjalmers ,

I make a new pull request to add a parameter in GtConfigSettings Interface. With this parameter, you can decide to display or not the column in column settings component.

I make this to solve my opened issue #181 .

Is that good for you ?

Thanks.

### CODE REVIEW

**Comment by hjalmers** [comment]
Thanks @thomasnisole, I'm going to take a look at it and hopefully it can be part of the next release:)

**Comment by thomasnisole** [comment]
Hey @hjalmers,

I come back to you to know what do you think about this feature after a look ?

Thanks.

**Comment by hjalmers** [comment]
Hi @thomasnisole, sorry I took so long...

**Comment by thomasnisole** [comment]
Hi @hjalmers ,

Thanks for merging !

**Pull request merged**
